import 'dart:io';

import 'package:mason/mason.dart';
import 'package:path/path.dart' as path;

/// {@template create_monorepo_service}
/// Service for creating new monorepo projects using Mason bricks.
/// {@endtemplate}
class CreateMonorepoService {
  /// {@macro create_monorepo_service}
  CreateMonorepoService({
    required Logger logger,
    MasonGenerator? generator,
  }) : _logger = logger,
       _generator = generator;

  final Logger _logger;
  final MasonGenerator? _generator;

  /// Creates a new monorepo project with the given variables.
  Future<void> create({
    required Map<String, dynamic> variables,
    required Directory outputDirectory,
  }) async {
    final projectName = variables['project_name'] as String;
    final progress = _logger.progress(
      'Creating monorepo project: $projectName',
    );

    try {
      // Get brick path
      final brickPath = await _getBrickPath();
      _logger.detail('Using brick at: $brickPath');

      // Load brick
      final brick = Brick.path(brickPath);
      _logger.detail('Brick loaded: ${brick.name}');

      // Generate using mason
      final generator = _generator ?? await MasonGenerator.fromBrick(brick);

      final target = DirectoryGeneratorTarget(outputDirectory);

      final generatedFiles = await generator.generate(
        target,
        vars: variables,
        logger: _logger,
        fileConflictResolution: FileConflictResolution.overwrite,
      );

      progress.complete('Generated ${generatedFiles.length} files');

      // Note: .envrc is already generated by the brick template
      // No need to create it manually here

      // Use paramCase for directory name (mason converts project_name to param-case)
      final projectDirName = projectName.replaceAll('_', '-');
      final workingDirectory = path.join(outputDirectory.path, projectDirName);

      // Run post-generation hook (generates app, console, widgetbook, backend)
      final hookProgress = _logger.progress('Running post-generation hooks');
      try {
        await generator.hooks.postGen(
          vars: variables,
          workingDirectory: workingDirectory,
        );
        hookProgress.complete('Post-generation hooks completed');
      } on Exception catch (e, stackTrace) {
        hookProgress.fail('Post-generation hooks failed');
        _logger
          ..err('Error running post_gen hook: $e')
          ..detail('$stackTrace');
        // Don't rethrow - hook failures shouldn't fail the entire creation
      }

      // Display success message
      _displaySuccessMessage(
        projectName: projectName,
        outputPath: outputDirectory.path,
      );
    } catch (e, stackTrace) {
      progress.fail('Failed to create project');
      _logger.err('Error: $e');
      _logger.detail('$stackTrace');
      rethrow;
    }
  }

  /// Gets the path to the monorepo brick.
  Future<String> _getBrickPath() async {
    // Try to find brick in the standard location
    final currentDir = Directory.current.path;

    // Check if we're in the bricks repo
    final brickPath = path.join(currentDir, 'bricks', 'monorepo');
    if (Directory(brickPath).existsSync()) {
      return brickPath;
    }

    // Check if brick exists in parent directory
    final parentBrickPath = path.join(currentDir, '..', 'bricks', 'monorepo');
    if (Directory(parentBrickPath).existsSync()) {
      return path.normalize(parentBrickPath);
    }

    // Check if we're inside template/co-bricks
    final templateBrickPath = path.join(
      currentDir,
      '..',
      '..',
      'bricks',
      'monorepo',
    );
    if (Directory(templateBrickPath).existsSync()) {
      return path.normalize(templateBrickPath);
    }

    throw Exception(
      'Could not find monorepo brick. '
      'Please run this command from the bricks repository root or ensure the brick exists at bricks/monorepo/',
    );
  }

  /// Displays success message with next steps.
  void _displaySuccessMessage({
    required String projectName,
    required String outputPath,
  }) {
    // Use paramCase for directory name (mason converts project_name to param-case)
    final projectDirName = projectName.replaceAll('_', '-');
    final projectPath = path.join(outputPath, projectDirName);

    _logger
      ..info('')
      ..success('🎉 Successfully created monorepo project: $projectName')
      ..info('')
      ..info('📁 Location: $projectPath')
      ..info('')
      ..info('Next steps:')
      ..info('  1. cd $projectName')
      ..info('  2. make start    # Initialize dependencies, git, and GitHub')
      ..info('')
      ..info('The "make start" command will:')
      ..info('  • Install Flutter dependencies')
      ..info('  • Initialize git repository')
      ..info('  • Create GitHub repository')
      ..info('  • Set up initial commit')
      ..info('');
  }
}
